name: multiarm
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - matplotlib
  - pytorch
  - numpy
  - seaborn
  - pip
  - tqdm
  - numba
  - pip:
    - gym
    - numpy-quaternion
    - ray
    - tensorboardx
    - pybullet
    - transforms3d
    - trimesh
    - PySimpleGUI
    - urdfpy